docker_build:
	docker build -t wxuerui/restaurants-reviews-api .

docker_run:
	docker run -dit --name restaurants-container -p 8080:8080 wxuerui/restaurants-reviews-api

docker_rm:
	docker rm -f restaurants-container

docker_clean:
	docker rm